import os, sys, argparse

def parse_args():
    parser = argparse.ArgumentParser(description="SpaDOT: Optimal transport modeling uncovers spatial domain dynamics in spatiotemporal transcriptomics.",
        prog='SpaDOT')
    subparsers = parser.add_subparsers(help='sub-command help.', dest='cmd_choice')

    # ===========================
    # Parser for performing preprocess for spatiotemporal transcriptomics data
    # -i, --data
    # -o, --output_dir
    # --prefix
    # --feature_selection
    # ============================
    preprocess_parser = subparsers.add_parser('preprocess', 
            help='(Recommended but optional) Perform data preprocessing and feature selection.')
    preprocess_parser.add_argument('-i', '--data', dest='data',
            required=True, type=str, help="We preprocess the data ")
    preprocess_parser.add_argument('-o', '--output_dir', dest='output_dir',
            type=str, help="Output directory to store preprocessed data. Default: the same as where the data locates.")
    preprocess_parser.add_argument('--prefix', dest='prefix',
            type=str, default='preprocessed_', help="Prefix for preprocessed data. Default: preprocessed_")
    preprocess_parser.add_argument('--feature_selection', dest='feature_selection',
            default=True, action="store_false",
            help="Whether performing feature selection. If not specified, feature selection option is chosen.")

    # ===========================
    # Parser for training SpaDOT model to obtain latent representations
    # -i, --data
    # -o, --output_dir
    # --prefix
    # --config
    # --save_model
    # ============================
    train_parser = subparsers.add_parser('train', help='Train a SpaDOT model.')
    train_parser.add_argument('-i', '--data', dest='data', 
            type=str, help="A anndata object containing time point information and spatial coordinates.")
    train_parser.add_argument('-o', '--output_dir', dest='output_dir', 
            type=str, help="Output directory to store latent representations. Default: the same as where the data locates.")
    train_parser.add_argument('--prefix', dest='prefix', 
            type=str, default='', help="Prefix for output latent representations. Default: ''")
    train_parser.add_argument('--config', dest='config',
            type=str, help="Path to the config file, in a yaml format.")
    train_parser.add_argument('--save_model', dest='save_model',
            default=False, action="store_true",
            help="Whether saving the trained model. If specified, the trained model will be stored in the output_dir as 'model.pt'.")

    ## ===========================
    # Parser for analyzing latent representations
    # -i, --data
    # -o, --output_dir
    # --prefix
    # ============================
    predict_parser = subparsers.add_parser('predict', help='Analyze the latent representations generated by SpaDOT model.')
    predict_parser.add_argument('-i', '--data', dest='data', 
            type=str, required=True,
            help="An anndata object containing latent representations.")
    predict_parser.add_argument('-o', '--output_dir', dest='output_dir', 
            type=str, help="Output directory to store analyses results. Default: the same as where the data locates.")
    predict_parser.add_argument('--prefix', dest='prefix', 
            type=str, default='', help="Prefix for output analyses results. Default: ''")
    
    args = parser.parse_args()
    print("User input arguments: ", args)
    return args


def main():
    args = parse_args()
    ## preprocessing
    if "preprocess" == args.cmd_choice:
        from SpaDOT import preprocess
        if not os.path.exists(args.data):
            sys.exit("The data does not exist! Please make sure the data is correctly specified.")
        preprocess.preprocess(args)
        
    ## train to obtain latent representations
    if "train" == args.cmd_choice:
        from SpaDOT import train
        if not os.path.exists(args.data):
            sys.exit("The preprocessed data does not exist! Please make sure the data is correctly specified.")
        train.train_SpaDOT(args)

    ## analyze latent representations
    if "predict" == args.cmd_choice:
        from SpaDOT import analyze
        if not os.path.exists(args.data):
            sys.exit("The latent representations does not exist! Please make sure the latent representations are correctly generated from the last step.")
        analyze.analyze(args)

if __name__ == "__main__":
    main()